<template>
	<div class="tabbar2">
    <ul>
      <li>
        <div>
          <h2>兑换券</h2>
          <p>兑换详情</p>
          <p>有效期至：<span>2018-08-20</span></p>
        </div>
        <span>兑换</span>
      </li>
      <li>
        <div>
          <h2>兑换券</h2>
          <p>兑换详情</p>
          <p>有效期至：<span>2018-08-20</span></p>
        </div>
        <span>兑换</span>
      </li>
      <li>
        <div>
          <h2>兑换券</h2>
          <p>兑换详情</p>
          <p>有效期至：<span>2018-08-20</span></p>
        </div>
        <span>兑换</span>
      </li>
      <li>
        <div>
          <h2>兑换券</h2>
          <p>兑换详情</p>
          <p>有效期至：<span>2018-08-20</span></p>
        </div>
        <span>兑换</span>
      </li>
      <li>
      <div>
        <h2>兑换券</h2>
        <p>兑换详情</p>
        <p>有效期至：<span>2018-08-20</span></p>
      </div>
      <span>兑换</span>
    </li>
      <li>
        <div>
          <h2>兑换券</h2>
          <p>兑换详情</p>
          <p>有效期至：<span>2018-08-20</span></p>
        </div>
        <span>兑换</span>
      </li>
      <li>
        <div>
          <h2>兑换券</h2>
          <p>兑换详情</p>
          <p>有效期至：<span>2018-08-20</span></p>
        </div>
        <span>兑换</span>
      </li>
      <li>
        <div>
          <h2>兑换券</h2>
          <p>兑换详情</p>
          <p>有效期至：<span>2018-08-20</span></p>
        </div>
        <span>兑换</span>
      </li>
    </ul>
  </div>
</template>

<script>
	export default {
		name: "tabbar2"
	}
</script>

<style>

</style>
